export interface IBadgeIconOption {
  value: string;
  label: string;
}

/** Curated FontAwesome icon choices for the badge catalog's icon picker. */
export const BADGE_ICON_OPTIONS: IBadgeIconOption[] = [
  { value: 'fa-solid fa-star', label: 'Star' },
  { value: 'fa-solid fa-award', label: 'Award' },
  { value: 'fa-solid fa-trophy', label: 'Trophy' },
  { value: 'fa-solid fa-medal', label: 'Medal' },
  { value: 'fa-solid fa-crown', label: 'Crown' },
  { value: 'fa-solid fa-gem', label: 'Gem' },
  { value: 'fa-solid fa-ribbon', label: 'Ribbon' },
  { value: 'fa-solid fa-certificate', label: 'Certificate' },
  { value: 'fa-solid fa-heart', label: 'Heart' },
  { value: 'fa-solid fa-thumbs-up', label: 'Thumbs Up' },
  { value: 'fa-solid fa-handshake', label: 'Handshake' },
  { value: 'fa-solid fa-hand-fist', label: 'Fist Bump' },
  { value: 'fa-solid fa-people-group', label: 'Teamwork' },
  { value: 'fa-solid fa-users', label: 'Team' },
  { value: 'fa-solid fa-user-check', label: 'Reliability' },
  { value: 'fa-solid fa-people-arrows', label: 'Collaboration' },
  { value: 'fa-solid fa-flag', label: 'Leadership' },
  { value: 'fa-solid fa-flag-checkered', label: 'Milestone' },
  { value: 'fa-solid fa-chess-king', label: 'Strategy' },
  { value: 'fa-solid fa-compass', label: 'Direction' },
  { value: 'fa-solid fa-bullseye', label: 'Focus' },
  { value: 'fa-solid fa-lightbulb', label: 'Innovation' },
  { value: 'fa-solid fa-rocket', label: 'Growth' },
  { value: 'fa-solid fa-fire', label: 'Energy' },
  { value: 'fa-solid fa-bolt', label: 'Impact' },
  { value: 'fa-solid fa-seedling', label: 'Initiative' },
  { value: 'fa-solid fa-leaf', label: 'Sustainability' },
  { value: 'fa-solid fa-shield-heart', label: 'Integrity' },
  { value: 'fa-solid fa-shield-halved', label: 'Trust' },
  { value: 'fa-solid fa-scale-balanced', label: 'Fairness' },
  { value: 'fa-solid fa-dove', label: 'Kindness' },
  { value: 'fa-solid fa-hands-holding-child', label: 'Support' },
  { value: 'fa-solid fa-hand-holding-heart', label: 'Generosity' },
  { value: 'fa-solid fa-face-smile', label: 'Positivity' },
  { value: 'fa-solid fa-face-laugh-beam', label: 'Fun' },
  { value: 'fa-solid fa-comments', label: 'Communication' },
  { value: 'fa-solid fa-bullhorn', label: 'Advocacy' },
  { value: 'fa-solid fa-microphone', label: 'Public Speaking' },
  { value: 'fa-solid fa-book', label: 'Learning' },
  { value: 'fa-solid fa-graduation-cap', label: 'Mentorship' },
  { value: 'fa-solid fa-brain', label: 'Problem Solving' },
  { value: 'fa-solid fa-magnifying-glass', label: 'Attention to Detail' },
  { value: 'fa-solid fa-check-circle', label: 'Quality' },
  { value: 'fa-solid fa-clock', label: 'Punctuality' },
  { value: 'fa-solid fa-calendar-check', label: 'Consistency' },
  { value: 'fa-solid fa-briefcase', label: 'Professionalism' },
  { value: 'fa-solid fa-chart-line', label: 'Performance' },
  { value: 'fa-solid fa-gears', label: 'Process Improvement' },
  { value: 'fa-solid fa-wrench', label: 'Troubleshooting' },
  { value: 'fa-solid fa-laptop-code', label: 'Technical Skill' },
  { value: 'fa-solid fa-code', label: 'Engineering' },
  { value: 'fa-solid fa-palette', label: 'Creativity' },
  { value: 'fa-solid fa-camera', label: 'Design' },
  { value: 'fa-solid fa-music', label: 'Culture' },
  { value: 'fa-solid fa-globe', label: 'Global Mindset' },
  { value: 'fa-solid fa-gift', label: 'Recognition' },
  { value: 'fa-solid fa-puzzle-piece', label: 'Adaptability' },
  { value: 'fa-solid fa-mountain', label: 'Resilience' },
  { value: 'fa-solid fa-dumbbell', label: 'Determination' },
  { value: 'fa-solid fa-person-running', label: 'Going Above & Beyond' },
];
